[package]
name = "nih_plug"
version = "0.1.0"
edition = "2021"
authors = ["Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license = "GPL-3.0-or-later"

[dependencies]
vst3-sys = { git = "https://github.com/RustAudio/vst3-sys.git" }
