[package]
name = "nih_plug"
version = "0.1.0"
edition = "2021"
authors = ["Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license = "GPL-3.0-or-later"

[workspace]
members = [
  "nih_plug_derive",
  "xtask",

  "plugins/gain",
]

[dependencies]
nih_plug_derive = { path = "nih_plug_derive" }

crossbeam = "0.8"
lazy_static = "1.4"
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
vst3-sys = { git = "https://github.com/robbert-vdh/vst3-sys.git", branch = "fix/atomic-reference-count" }
widestring = "1.0.0-beta.1"
