[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
authors = ["Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license = "ISC"

[dependencies]
nih_plug_xtask = { path = "../nih_plug_xtask" }
