[package]
name = "nih_plug_derive"
version = "0.1.0"
edition = "2021"
authors = ["Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license = "ISC"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
